version: "{branch}.{build}"
image:
  - "Visual Studio 2015"
cache:
  - '%USERPROFILE%\.m2\repository'
  - '%USERPROFILE%\.m2\wrapper'
init:
  - git config --global core.autocrlf true
build:
  verbosity: detailed
build_script:
  - 'mvnw.cmd clean install'
  - 'mvnw.cmd site'
  - 'RD /S /Q %USERPROFILE%\.m2\repository\kr\motd\maven\sphinx-maven-plugin'
test: off
matrix:
  fast_finish: true
