version: "{branch}.{build}"
image:
  - "Visual Studio 2015"
environment:
  PATH: "C:\\msys64\\usr\\bin;%PATH%"
  matrix:
    - APPVEYOR_BITS: 32
    - APPVEYOR_BITS: 64
cache:
  - '%HOME%\.m2\repository'
  - '%HOME%\.m2\wrapper'
init:
  - git config --global core.autocrlf true
build:
  verbosity: detailed
build_script:
  - 'mvnw.cmd clean install'
  - 'mvnw.cmd site'
  - 'RD /S /Q %HOME%\.m2\repository\kr\motd\maven\sphinx-maven-plugin'
test: off
matrix:
  fast_finish: true
